#!/bin/bash

export PATH="/opt/rnaediting/cwl:/opt/rnaediting/py:/opt/conda/bin:/usr/bin:$PATH"


# this was used when running various commands like samtools etc from outise the container
# calling singularity rnaediting.img samtools
#"$@"


if [ $# -eq 0 ]
then
    echo
    cat /documentation/usage.txt
else
    echo rnaediting ${@:1}
    rnaediting2strands.workflow.cwl $@
fi