#!/bin/bash

export PATH="/opt/sailor/bin:/opt/sailor/cwl:/opt/sailor/py:/opt/conda/bin:/usr/bin:$PATH"


if [ $# -eq 0 ]
then
    echo
    cat /documentation/usage_cwl.txt
    read -t30 -p "Do you want me to copy now into your current directory an example of data input files and a job template (y/-): "
    if [[ $REPLY == "y" ]]
    then
       cp -r /opt/sailor/example/* ./
    fi

else
    /opt/sailor/bin/sailor $1
fi
